### This file is just for Document purpose and development testing, It is not for Production commit

### Sign in for Auth

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Create form

POST http://localhost:3000/v1/form
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MTI3MjgwNDEsImV4cCI6MTcxMjcyODM0MX0.e0lC44zf1eXlMsky1aN3RN_VepKQJxjtCJD-2GVznXg

{
    "uniqueId": "uuid",
    "title": "User",
    "name": "string",
    "email": "email",
    "phonenumber": "number",
    "isGraduate": "boolean"
}


### Fill form

POST http://localhost:3000/v1/fill_data?form_title=User
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MTI3MjgwNDEsImV4cCI6MTcxMjcyODM0MX0.e0lC44zf1eXlMsky1aN3RN_VepKQJxjtCJD-2GVznXg

{
    "uniqueId": "21d44798-933b-43ea-8568-ca374e74ea53",
    "name": "user name 3",
    "email": "test3@test.com",
    "phonenumber": "+919876543213",
    "isGraduate": true
}

### Retrive form values

GET http://localhost:3000/v1/fill_data?form_title=User
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MTI2ODY0OTEsImV4cCI6MTcxMjY4NjYxMX0.7sEHqmAL0a2L_ZBf9NylOHKHYGI42Q5ztES5UkFx5mQ
